site_name: Telephoto
site_url: https://saket.github.io/telephoto/
repo_name: telephoto
repo_url: https://github.com/saket/telephoto
site_description: 'Building blocks for designing media experiences in Compose UI'
site_author: Saket Narayan
copyright: 'Copyright &copy; 2023 Saket Narayan'
remote_branch: gh-pages

theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: assets/logo_192.png
  favicon: assets/logo_192.png
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link # Synchronize code tabs.
    - content.code.copy # Show a copy button in code blocks.
    - navigation.instant # Instant loading of pages. Behave like a Single Page Application.
    - toc.integrate
extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:  # Table of contents.
      permalink: true # Anchor linking with headings.
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret # Underlines.
  - admonition  # Warning call-outs.

plugins:
  - search
  - macros # For extra.versions.telephoto below.
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: false
      video_autoplay: true
      video_loop: true
      css_style:
        width: "100%"
        height: "30rem"

extra:
  versions:
    telephoto: '0.6.2' # Env var for the latest version on maven.

nav:
  - 'Overview': index.md
  - 'Zoomable Image':
      - 'Overview': zoomableimage/index.md
      - 'Sub-sampling': zoomableimage/sub-sampling.md
      - 'Custom image loaders': zoomableimage/custom-image-loaders.md
      - 'Recipes': zoomableimage/recipes.md
  - 'Modifier.zoomable()':
      - 'Overview': zoomable/index.md
      - 'Recipes': zoomable/recipes.md
