[versions]
minSdk = "23"
compileSdk = "33"
kotlin = "1.8.10"
jetbrains-compose = "1.4.0"
agp = "7.4.2"
compose-runtime = "1.4.3"
compose-ui = "1.4.3"
compose-ui-material3 = "1.1.0-rc01"
accompanist = "0.30.0"
androidx-compose-compiler = "1.4.4"
androidx-appcompat = "1.6.1"
androidx-activity = "1.7.1"
androidx-ktx = "1.10.0"
androidx-ktx-palette = "1.0.0"
androidx-test = "1.5.0"
testParamInjector = "1.11"
junit = "4.13.2"
truth = "1.1.3"
coil = "2.4.0"
glide = "4.15.1"
turbine = "0.12.3"
paparazzi = "1.2.0"
molecule = "0.8.0"
coroutines = "1.7.0-RC"
appyx = "1.1.1"
mavenPublish = "0.24.0"
dropshots = "0.4.0"
dropboxDiffer = "0.0.1"
emulatorWtf = "0.9.5"       # https://docs.emulator.wtf/changelog/
emulatorWtf-cli = "0.9.8"   # https://docs.emulator.wtf/changelog/
okio = "3.3.0"
okhttp-mockWebServer = "4.11.0"
dokka = "1.8.10"

[libraries]
plugin-paparazzi = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-jetbrains-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }
plugin-dropshots = { module = "com.dropbox.dropshots:dropshots-gradle-plugin", version.ref = "dropshots" }
plugin-emulatorWtf = { module = "wtf.emulator:gradle-plugin", version.ref = "emulatorWtf" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-ktx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-ktx" }
androidx-ktx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-ktx-palette" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity"}

androidx-test-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
# TODO remove compose libs in favor of declaring via jetbrains compose plugin
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose-ui" }
compose-ui-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-ui-material3" }
compose-ui-materialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-ui" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-activityManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }

accompanist-drawablePainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil" }

glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakeFileSystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp-mockWebServer" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
testParamInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParamInjector" }
dropshots = { module = "com.dropbox.dropshots:dropshots", version.ref = "dropshots" }
dropboxDiffer = { module = "com.dropbox.differ:differ", version.ref = "dropboxDiffer" }

appyx = { module = "com.bumble.appyx:core", version.ref = "appyx" }
